version: "3.7"
services:
  postgres:
    image: postgres:13
    container_name: "${POSTGRES_CONTAINER_NAME}"
    restart: "no"
    environment:
      POSTGRES_DB: "${POSTGRES_DATABASE}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "54320:5432"
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 128M